### ISSUE TITLE
Adding Processors to the Sprockets environment?

### ISSUE THREAD

**Issue by danott** [javan/blade#8]
Is there currently a way to add additional [Processors](https://github.com/rails/sprockets#processor-interface) to the Sprockets environment? If not, is this a change that you'd consider accepting contributions for?

**Comment by javan** [comment]
Do you mean a custom processor that Sprockets doesn't know how to autoload?

**Comment by danott** [comment]
Please forgive the ignorance, because I am not 100% familiar with how Sprockets autoloads processors, so I am not sure. But my best guess is that the answer to that question would be yes.

As a litmus test, I was trying to process a single file using the `sprockets-es6` gem. I added `gem "sprockets-es6"` to my `Gemfile`, and changed the extension of my test file from `test.js` to `test.es6`. After this change, `blade` could no longer resolve the logical path. Making the same change from `test.js` to `test.coffee`, blade could resolve the logical path.

From what I can infer, [this is the autoloading code](https://github.com/TannerRogalsky/sprockets-es6/blob/master/lib/sprockets/es6.rb#L87-L90)?

**Comment by javan** [comment]
Sorry, I wasn't very clear. By "know how to autoload" I meant processors that Sprockets has built in support for: https://github.com/rails/sprockets/blob/master/lib/sprockets/autoload.rb. `sprockets-es6` is not one of them.

I'm definitely willing to consider a patch that adds a general `require` or `gems` configuration for `blade.yml`. In the meantime, you could do this in a custom Rake task:
```ruby
# Rakefile
require "blade"
require "sprockets/es6"

namespace :blade do
  task :runner do
    Blade.start(interface: :runner)
  end
end
```

**Comment by danott** [comment]
Thanks for the clarification. Overriding the Rake task with my customization needs feels like a good path to test this out for now. If I find I need it across multiple projects, I'll go down the path of hooking into `blade.yml` and submit a PR. 😄 Thanks!
